substitutions:
  name: switch-chodba
  friendly_name: "Spínač chodba"
  button_gpio: GPIO14
  relay_gpio: GPIO13
  project_name: "athom.mini-switch"
  project_version: "1.1"
  light_restore_mode: ALWAYS_ON

esphome:
  name: "${name}"
  name_add_mac_suffix: true
  project:
    name: "${project_name}"
    version: "${project_version}"

esp8266:
  board: esp8285
  restore_from_flash: true

api:

logger:
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

captive_portal:

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password  

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-mini-switch.yaml

script:
  - id: hass_light_toggle
    then:
      if:
        condition:
          api.connected:
        then:
          - if:
              condition:
                light.is_off: relay
              then:
                # Turn the relay back on and turn on the light.
                - light.turn_on: relay

                - homeassistant.service:
                    service: script.prepnuti_svetla_na_chodbe
              else:
                # Have Home Assistant toggle the light.
                - homeassistant.service:
                    service: script.prepnuti_svetla_na_chodbe
        else:
          # When HA is unavailable, toggle the relay.
          - light.toggle: relay

binary_sensor:
  # Button on mini switch
  - platform: gpio
    pin:
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Power Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at least 4s
        then:
          - button.press: Reset

  - platform: status
    name: "${friendly_name} Status"
  - platform: gpio
    pin:
      number: $button_gpio
    name: Tlačítko světlo chodba
    id: tlacitko
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - script.execute: hass_light_toggle

output:
  - platform: gpio
    id: relay_output
    pin: GPIO13

button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
    id: Reset

light:
  - platform: status_led
    name: "${friendly_name} Blue LED"
    disabled_by_default: true
    pin:
      number: GPIO4
      inverted: true
  - platform: binary
    id: relay
    output: relay_output
    restore_mode: ALWAYS_ON      

sensor:
  - platform: uptime
    name: "${friendly_name} Uptime"
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
      disabled_by_default: true

time:
  - platform: sntp
    id: my_time
