substitutions:
  name: switch-chodba-cf6c6b
packages:
  athom.mini-switch: github://athom-tech/athom-configs/athom-mini-switch.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: +EgW6Cb1WPdapYH9jE44r6tkI3sozIp7gNVmUwFmj98=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
