substitutions:
  name: chodba-switch
  friendly_name: "Tlačítko chodba"
  project_name: "sonoff.minir4-extreme"
  project_version: "1.1"
  light_restore_mode: ALWAYS_OFF
  ip_address: 192.168.1.169
esphome:
  name: "${name}"
  name_add_mac_suffix: false
  project:
    name: "${project_name}"
    version: "${project_version}"

<<: !include components/ota.yaml
<<: !include components/wifi.yaml

esp32:
  board: esp32dev
  framework:
    type: arduino

api:

logger:
  baud_rate: 0

mdns:
  disabled: false

web_server:
  port: 80

captive_portal:

sensor:
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal Strength
    update_interval: 90s
    entity_category: "diagnostic"

  - platform: uptime
    name: ${friendly_name} Uptime
    update_interval: 300s
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ssid:
      name: Connected SSID
    ip_address:
      name: IP Address
    dns_address:
      name: DNS Address

time:
  - platform: sntp
    id: my_time

#######################################
# Device specific Config Begins Below #
#######################################

status_led:
  pin:
    number: GPIO19
    inverted: true

output:
  # Physical relay on GPIO
  - platform: gpio
    pin: GPIO26
    id: relay_1

light:
  - platform: binary
    id: mini_relay
    name: "${friendly_name} Light"
    icon: mdi:ceiling-light-multiple-outline
    restore_mode: ${light_restore_mode}
    output: relay_1

binary_sensor:
  - platform: gpio
    name: s1
    pin: GPIO27
    id: s1
    filters:
      - invert:
      - delayed_off: 50ms
    on_press:
      - script.execute: hass_light_toggle

script:
  - id: hass_light_toggle
    then:
      if:
        condition:
          api.connected:
        then:
          - if:
              condition:
                light.is_off: mini_relay
              then:
                # Turn the relay back on and turn on the light.
                - light.turn_on: mini_relay

                - homeassistant.service:
                    service: script.prepnuti_svetla_na_chodbe
              else:
                # Have Home Assistant toggle the light.
                - homeassistant.service:
                    service: script.prepnuti_svetla_na_chodbe
        else:
          # When HA is unavailable, toggle the relay.
          - light.toggle: mini_relay






