substitutions:
  name: sklep-chodba
  friendly_name: "Světlo chodba"
packages:
  athom.mini-switch: !include templates/athom-mini-switch.yaml
esphome:
  name_add_mac_suffix: false

<<: !include components/ota.yaml
<<: !include components/wifi.yaml