substitutions:
  name: kuchyne-sporak-svitidlo
  friendly_name: "Světlo kuchyně - sporák"
packages:
  athom.mini-switch: !include templates/athom-mini-switch-with-button.yaml
esphome:
  name_add_mac_suffix: false


ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Athom Switch Fallback Hotspot"
    password: !secret esphome_wifi_fallback_password
