substitutions:
  name: kuchyne-sporak-svitidlo
  friendly_name: "Světlo kuchyně - sporák"
packages:
  athom.mini-switch: !include templates/athom-mini-switch-with-button.yaml
esphome:
  name_add_mac_suffix: false

<<: !include components/ota.yaml
<<: !include components/wifi.yaml